import { Component, OnInit } from '@angular/core';
import { NumberValueAccessor } from '@angular/forms';
import { Router } from '@angular/router';

@Component({
  selector: 'app-user-profile',
  templateUrl: './user-profile.component.html',
  styleUrls: ['./user-profile.component.css']
})
export class UserProfileComponent implements OnInit {

  user = {
    pseudo : "chouPi456",
    roles: [{roleName :"admin"},
            {roleName :"organisatrice"},
            {roleName :"cuisinière"},
            ], 
    presentation : "Bonjour ! j'aime cuisiner et je suis quelqu'un de sympas.",
    recettes : [ {"id":1,"nom":"Soupe au Lardon","dateCreation":"2019-11-22","dateDerniereEdition":"2019-11-22","tempsPreparation":50,"tempsCuisson":80,"description":"Une soupe bien grasse et bien degeulasse, que je déconseil fortement de manger.","listeEtapes":[{"numero":2,"description":"ajoutez les lardon"},{"numero":1,"description":"portez à ébulition l'eau dans une casserol"},{"numero":3,"description":"utilisez un mixeur pour broyer les lardon"}],"commentaires":null,"ingredients":null,"auteur":null},
                {"id":2,"nom":"Le chat à la moutarde","dateCreation":"2019-11-22","dateDerniereEdition":"2019-11-22","tempsPreparation":15,"tempsCuisson":60,"description":"Fort de mes expériences culinaires et sur l'insistance de certains cordons bleus introvertis, je vous livre une recette originale qui devrait vous faire lècher les babines et friser la moustache.","listeEtapes":[{"numero":3,"description":"Faites suer la garniture aromatique (échalote, oignons et persil) à feu doux en décollant les sucs de cuisson du chat."},{"numero":7,"description":"Pour finir... J'utilise le même vin à table que pour la cuisson. Ce plat est encore meilleur réchauffé le lendemain. Servez-le avec des tagliatelles fraîches."},{"numero":5,"description":"Un quart d'heure avant la fin de la cuisson, ajoutez les champignons coupés en quartier et le foie du chat."},{"numero":2,"description":"Faites revenir le chat dans un peu d'huile à feu moyen, puis enlevez les morceaux du faitout."},{"numero":4,"description":"Remettez les morceaux de chat (sauf le foie) dans le faitout, et mouillez avec 1/2 l de vin blanc sec. Salez et poivrez."},{"numero":1,"description":"Salez, poivrez et badigeonnez les morceaux de chat avec de la moutarde forte (n'hésitez pas sur la quantité, la moutarde perd de sa force avec la cuisson) puis farinez les morceaux."},{"numero":6,"description":"Avant de dresser le chat, rectifiez l'assaisonnement et liez la sauce à la maïzena ou avec un beurre manié (moitié beurre, moitié farine à pétrir avant d'ajouter par petite quantité à la sauce en faisant bouillir)."}],"commentaires":null,"ingredients":null,"auteur":null},
                {"id":14,"nom":"Le Velouté Ferme","dateCreation":"2017-04-15","dateDerniereEdition":"2017-04-15","tempsPreparation":142,"tempsCuisson":63,"description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.","listeEtapes":[{"numero":5,"description":"Allonger la farine"},{"numero":3,"description":"Façonner les pâtes"},{"numero":1,"description":"Frotter le thon au naturel"},{"numero":4,"description":"Enfermer le curry"},{"numero":2,"description":"Dissoudre la pâte à tarte brisée prête à dérouler"}],"commentaires":null,"ingredients":null,"auteur":null},
                {"id":23,"nom":"L'Aigre Exquis","dateCreation":"2005-11-11","dateDerniereEdition":"2005-11-11","tempsPreparation":178,"tempsCuisson":18,"description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.","listeEtapes":[{"numero":1,"description":"Décortiquer la cannelle"},{"numero":3,"description":"Badigeonner un fromage à pâte dur"},{"numero":2,"description":"Effeuiller le court-bouillon"},{"numero":6,"description":"Frotter le curry"},{"numero":5,"description":"Chemiser la cannelle"},{"numero":4,"description":"Étuver les boîtes de champignons de paris émincés ou entiers"},{"numero":7,"description":"Couper le lait"}],"commentaires":null,"ingredients":null,"auteur":null},
                {"id":34,"nom":"Le Tendre Fondant","dateCreation":"2005-06-04","dateDerniereEdition":"2005-06-04","tempsPreparation":190,"tempsCuisson":143,"description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.","listeEtapes":[{"numero":8,"description":"Froisser une tablette de chocolat pour la cuisine"},{"numero":3,"description":"Couper le thon au naturel"},{"numero":5,"description":"Diluer les tomates pelées"},{"numero":1,"description":"Ajouter la crème fraîche liquide"},{"numero":6,"description":"Colorer la salade ou de la mâche (elle accompagne aussi bien les tartes, quiches salées que les plats d’hiver comme tartiflette…)"},{"numero":4,"description":"Essorer la pulpe de tomates"},{"numero":7,"description":"Effiler le court-bouillon"},{"numero":2,"description":"Assaisonner la pulpe de tomates"}],"commentaires":null,"ingredients":null,"auteur":null},
                {"id":27,"nom":"Le Gélatineux Brûlé","dateCreation":"2004-08-17","dateDerniereEdition":"2004-08-17","tempsPreparation":146,"tempsCuisson":1,"description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.","listeEtapes":[{"numero":1,"description":"Fourrer les herbes de Provence"},{"numero":4,"description":"Couvrir les fruits et les légumes de saisons"},{"numero":5,"description":"Dresser le citron"},{"numero":3,"description":"Additionner le beurre"},{"numero":2,"description":"Étaler un fromage à pâte dur"}],"commentaires":null,"ingredients":null,"auteur":null},
                {"id":40,"nom":"Le Doux Sec","dateCreation":"2004-05-20","dateDerniereEdition":"2004-05-20","tempsPreparation":148,"tempsCuisson":70,"description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.","listeEtapes":[{"numero":1,"description":"Diluer les cubes de bouillon de légumes"},{"numero":5,"description":"Fariner la pâte à tarte brisée prête à dérouler"},{"numero":9,"description":"Compléter le citron"},{"numero":8,"description":"Façonner le sucre vanillé"},{"numero":3,"description":"Couvrir les tomates pelées"},{"numero":2,"description":"Garnir le court-bouillon"},{"numero":6,"description":"Déglacer les noix de muscade ou muscade moulue"},{"numero":4,"description":"Égrapper les pâtes"},{"numero":7,"description":"Égrener les échalotes"}],"commentaires":null,"ingredients":null,"auteur":null},
                {"id":37,"nom":"Le Mousseux Surprenant","dateCreation":"2002-02-23","dateDerniereEdition":"2002-02-23","tempsPreparation":62,"tempsCuisson":70,"description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.","listeEtapes":[{"numero":4,"description":"Foncer un fromage à pâte dur"},{"numero":3,"description":"Coller le beurre"},{"numero":6,"description":"Écailler le concentré de tomates"},{"numero":10,"description":"Dresser l'ail"},{"numero":11,"description":"Décortiquer le sucre vanillé"},{"numero":8,"description":"Assaisonner la pâte à tarte brisée prête à dérouler"},{"numero":1,"description":"Coller les échalotes"},{"numero":14,"description":"Concasser les oignons"},{"numero":12,"description":"Gratiner les cubes de bouillon de légumes"},{"numero":2,"description":"Effiler le coriandre moulue"},{"numero":9,"description":"Assaisonner les raisins secs"},{"numero":5,"description":"Concasser   un pot de miel"},{"numero":7,"description":"Effeuiller la crème fraîche semi épaisse"},{"numero":13,"description":"Dénoyauter le court-bouillon"}],"commentaires":null,"ingredients":null,"auteur":null},
                {"id":4,"nom":"Le Cru Lourd","dateCreation":"1997-02-25","dateDerniereEdition":"1997-02-25","tempsPreparation":69,"tempsCuisson":63,"description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.","listeEtapes":[{"numero":6,"description":"Battre la crème fraîche liquide"},{"numero":2,"description":"Chiffonner les raisins secs"},{"numero":4,"description":"Démouler les gâteaux secs comme les petits beurres ou les speculoos"},{"numero":9,"description":"Égrener le coriandre moulue"},{"numero":7,"description":"Braiser la fécule de maïs ou maïzena"},{"numero":8,"description":"Décorer l’huile de tournesol ou autre (colza, pépins de raisins..)"},{"numero":3,"description":"Chemiser les fruits et les légumes de saisons"},{"numero":5,"description":"Arroser les feuilles de laurier"},{"numero":10,"description":"Ébarber le fromage blanc"},{"numero":1,"description":"Écraser le sucre blanc ou roux"}],"commentaires":null,"ingredients":null,"auteur":null},
               ]
  }

  constructor(private router: Router) { }

  ngOnInit() {
  }

  public goToRecette(id: number): void{
    this.router.navigateByUrl("recettes/" + id)
  }



}
